### ISSUE TITLE
wxPython dependency 

### ISSUE THREAD

**Issue by jd-daniels** [PIRCImagingTools/NeBSS#1]
Our environment meets all the requirements. But I'm seeing this:

`Traceback (most recent call last):
  File "nebss_gui.py", line 2, in <module>
    import NeBSS.ui.nebss_gui
  File "/home/<me>/nebss/NeBSS/NeBSS/ui/nebss_gui.py", line 515, in <module>
    class SplashScreen(wx.SplashScreen):
AttributeError: 'module' object has no attribute 'SplashScreen'
`
Is there a particular wxPython version that this relies on? I've installed 4.0.1.

Thanks.

**Comment by rafaceschin** [comment]
Hi we use wxPython 3.0 
Specifically, the python-wxgtk3.0 from the Ubuntu repositories. 
Let me know if that works for you.

**Comment by jd-daniels** [comment]
Yes that works. Thanks.
